### ISSUE TITLE
csvsql: Type inference desired for some columns, not others.

### ISSUE THREAD

**Issue by robertcatgithub** [onyxfish/csvkit#309]
Re-opening this issue:

https://github.com/onyxfish/csvkit/issues/291

This issue I reported can be avoided by "--no-inference". But now NULL is inserted as the literal string "NULL"

**Comment by jpmckinney** [comment]
* `echo "a,b\n," | csvsql` inserts NULL
* `echo "a,b\nNULL,NULL" | csvsql` inserts NULL
* `echo "a,b\n," | csvsql --no-inference` inserts empty string
* `echo "a,b\nNULL,NULL" | csvsql --no-inference` inserts "NULL"

This is expected behavior. "No inference" really means "No inference". It won't turn the string "NULL" into the NULL value.

For posterity, for #291:

* `echo "a,b\nY,T\nN,F" | csvsql`
* `echo "a,b\nY,T\nN,F" | csvsql --no-inference`

**Comment by jpmckinney** [comment]
Ah, renaming issue now that I understand.

**Comment by onyxfish** [comment]
I suppose there is a case to be made that nulls aren't a "type", though this seems like it's a pretty slippery slope. Concur with calling it a low-priority feature.

**Comment by jpmckinney** [comment]
Merging into #151.
