### ISSUE TITLE
Unexpected behavior sorting floats

### ISSUE THREAD

**Issue by AbeHandler** [onyxfish/csvkit#341]
Hi. I just tried to sort the following data with csvkit. It looks like it is doing a sort -- but not what you would expect. 

https://gist.github.com/AbeHandler/7644dddcf46eb86515cd

In that gist, testdata = small.test (on the command line)

**Comment by ryanpitts** [comment]
Figured I'd hack on this one a bit. But unless I'm missing something, what looks like unexpected behavior is actually just csvsort's default assumption that the first row is headers. Normal behavior is (basically) to strip the header row, sort the actual rows, then insert the header row back on top before output, right?

The first row of test data posted in this issue clearly isn't *supposed* to be a header, but if you assume that it is, you're actually getting expected results. They're just visually unexpected if you aren't thinking about headers.

![screen shot 2015-01-30 at 8 22 08 pm](https://cloud.githubusercontent.com/assets/56477/5986776/e4b90646-a8bd-11e4-8719-e752a5158275.png)

If you manually add a header row, no problems.

![screen shot 2015-01-30 at 8 24 36 pm](https://cloud.githubusercontent.com/assets/56477/5986779/0a047520-a8be-11e4-8065-d782fecf0a69.png)

Or if you pass --no-header-row as an arg, it also works as expected.

![screen shot 2015-01-30 at 8 19 48 pm](https://cloud.githubusercontent.com/assets/56477/5986768/7ac7e09a-a8bd-11e4-9739-7e856bed1025.png)

So ... I don't *think* there's an actual issue here. Am I missing something?

**Comment by jpmckinney** [comment]
Correct. Thanks @ryanpitts !
