### ISSUE TITLE
csvjoin should throw more explicit errors when column names don't match because of whitespace

### ISSUE THREAD

**Issue by facundofarias** [onyxfish/csvkit#364]
I was trying to perform a csvjoin, and I was getting the following output: 
*Column identifier "xxx" is neither an integer, nor a existing column's name.*
The thing was, that the field name contained a blank space before the name. Perhaps it could be helpful to trim all the blank spaces at the beginning and at the end of the column name.
What do you think? If you agree and give me some hints, I can do it :)

Thanks

**Comment by onyxfish** [comment]
Hi Facundo! Thanks for the suggestion. My rule of thumb for csvkit is that it should never modify the data except under very explicit circumstances (conversion, for example). I don't want it doing magic manipulation like this, because then if I implement it as part of a data pipeline it might change my data in ways I don't foresee. I know it may seem like a small thing, but I think it's best that csvkit not manipulate the data just in case, in some outside case that whitespace is significant to the original data.

That being said, I can definently see an argument for a more explicit error message, and I've updated the ticket name accordingly. Thanks again for opening the issue!

**Comment by facundofarias** [comment]
Makes sense. :+1: 
Thanks

**Comment by smr99** [comment]
I understand the argument against "magic manipulation".  On the other hand, given a CSV file where  column names have a leading space, I'm stuck on how to extract them.

$ csvcut -n data.csv 
  1: sec
  2:  usec
  3:  RTI Frame Count

It's probably not apparent here, but there is a one space indentation for colums 2 and 3: the first line is "sec, usec, RTI Frame Count".  So this obviously fails:

$ csvcut -c usec data.csv | csvstat
Column identifier "usec" is neither an integer, nor a existing column's name.

So I try quoting:
$ csvcut -c " usec" data.csv | csvstat
Column identifier "usec" is neither an integer, nor a existing column's name.

Hmmm: somewhere in the command parsing, the leading space is stripped out.  This is cygwin and I tried a few more variations ' usec', "\ usec", and again without quotes (\ usec).  No joy.  

I can use the column number, of course.  But is there any way to use the column name?  Ultimately, I want this to work with Windows command shell, which has different rules for argument parsing...

On the other hand, even if there is a way to specify a command-line argument with a leading space, it is a bit of a nuisance.  So my request would be the same as the original request on this ticket: a way to strip leading and trailing space from a column name.  I understand if you don't want to automagically do so; a command argument to enable this stripping is fine with me.

**Comment by jpmckinney** [comment]
The `strip` call originates from 93a3f178.

**Comment by jpmckinney** [comment]
I don't see what bug the stripping could potentially have solved. If people are declaring columns like `-c "foo,      bar"`, then they are doing it wrong...
