### ISSUE TITLE
Suggested speedup: infer types from first N records

### ISSUE THREAD

**Issue by fwhigh** [onyxfish/csvkit#387]
I love csvkit, but it doesn't appear to scale super well with large files.  One guess I have as to why this is the case is the column type inference, which I presume is run on the full data set.  

I would be willing to accept some probability of error in inferred column type by performing the inference over just the first N records, where N is specified by me via the CLI.  I bet that usually the first N=10 or 100 records are enough to get the types right.

Is column inference the limiting operation in the time complexity of, say, csvlook?

**Comment by onyxfish** [comment]
Hi and thanks for the suggestion. This is something I've been round-and-round with many times. You're right that it doesn't scale super well and this a known issue. I've explicitly optimized for human time via  simple interface, rather than for optimal processing of large files, which are a relative edge case. The issue with implementing a "sniff limit" for type inference is that it creates a myriad of error cases for when the type inference is wrong. If I presume a column is `float` because the first 100 lines were but then the 101st line is `None`, now I've created a wide range of possible side-effects that need to be handled in `csvstat` and all the other tools that use inference. Rather than inherit this complexity I've opted to keep the type inference global and defer high-performance optimizations to custom tooling.

If there is a better solution to this I'm all ears, but it's definitely something I've thought long and hard about.

**Comment by fwhigh** [comment]
I've heard anecdotally and offhand that Excel does this, but if so I'm sure the error handling there is sophisticated as you said.

The csvkit feature that I derive the most value from, by a long shot, is getting string fields right.  I actually don't need the other fields' types to be inferred, meaning I want integers and floats to be represented as-is in the output anyway.  I would normally do it in awk in a single-pass streaming fashion but it's a pain in the ass to correctly split out string fields that also have commas.

I realize that the type needs to be right for csvgrep and related functionality, but the times I need string columns to be correctly parsed are generally different than the times I need to filter out rows.  For example, I might run csvcut to select a couple columns and be done with it.  Getting the string fields right is the main thing I'm looking for, and inferring non-string field types is not needed.  Csvcut could be super fast if we allow for just top N inference.

What are your thoughts around enabling top N inference for a defined subset of tasks?

**Comment by jpmckinney** [comment]
Just noting that csvcut doesn't perform inference.
